import values from "lodash/values"

export enum NavigableRoute {
  HomeTabs = "hometabs",

  DashboardStack = "hometabs/dashboard-stack",
  Dashboard = "dashboard",
  DashboardEdit = "dashboard-edit",
  DashboardReady = "dashboard-ready",

  TodoStack = "hometabs/todo-stack",
  Todos = "todos",

  ResourceStack = "hometabs/resource-stack",
  Resources = "resources",
  ModalStack = "ModalStack",
  PortfolioStack = "hometabs/portfolio-stack",
  Portfolio = "portfolio",
  PortfolioReady = "PortfolioReady",
  ProfileStack = "hometabs/profile-stack",
  ProfilePreview = "ProfilePreview",
  ProfileSettings = "ProfileSettings",
  ProfileLoading = "loading",
  Profile = "profile",
  ProfilePasswordChange = "password-change",
  ProfileAccount = "account-Account",
  ProfileImageStack = "profile-image-stack",
  ProfileImageSelect = "profile-image-stack/profile-image-select",
  ProfileImagePicker = "profile-image-stack/gallery",
  ProfileCameraRoll = "profile-image-stack/camera",

  AuthStack = "auth-stack",
  AuthLanding = "landing",
  AuthEmailLanding = "email-landing",
  AuthLogin = "login",
  AuthSignup = "signup",
  SignUpRegistered = "signup-registered",
  SignUpCongrats = "signup-congrats",
  SignUpAccount = "signup-account",
  SignUpNDA = "signup-nda",
  SignUpApa = "signup-apa",
  AuthGetUserEmail = "get-user-email",
  AuthMultifactor = "multifactor",
  PasswordReset = "password-reset",
  ResetConfirm = "ResetConfirm",
  OneTimePassword = "one-time-password",

  OnboardingStack = "onboarding-stack",
  OnboardingFlowStep1 = "onboard-step-1",
  OnboardingFlowStep2 = "onboard-step-2",
  OnboardingFlowStep3 = "onboard-step-3",
  OnboardingFlowStep4 = "onboard-step-4",
  OnboardingFlowStep5 = "onboard-step-5",

  NotificationPreferences = "settings-notification-preferences",
  VerifyEmail = "verify-email",
  VerifyPhoneStack = "verifyphonestack",
  VerifyPhone = "verifyphonestack/verify-phone",
  VerifyPhonePrompt = "verifyphonestack/verify-phone-prompt",
  ConfirmPhoneCode = "verifyphonestack/confirm-phone-code",
  AccountMFAStack = "account-mfa-stack",
  OTPChallenge = "account-mfa-stack/otp-challenge",
  EmailChallengeInfo = "account-mfa-stack/email-challenge-info",
  EmailChallenge = "account-mfa-stack/email-challenge",
  AccountPhoneNumber = "account-mfa-stack/account-phone-number",

  ModalCard = "modal-card",
  WebViewScreen = "webview",
  PermissionsDialog = "permissions_dialog",
  LocationPicker = "location-picker",
  AffirmRejectDialog = "affirm-reject-dialog",
  ErrorDialog = "error-dialog",
  CustomizeTheme = "customize-theme",
  CloseWebview = "App.CloseWebView",

  UpdateApp = "update-app",
  DevServerSetting = "dev-server-setting",
}

export const navigableRoutes: string[] = values(NavigableRoute)
