export const AVATAR_SIZE = 48
export const MARGIN_USER_CONTENT = 4
export const MARGIN_STAR_RATING_CONTAINER = 1
export const AVATAR_SIZE_LARGE = 96
export const AVATAR_SIZE_MEDIUM = 74
export const DEALER_BADGE_OFFSET_STEP = 11
export const AVATAR_SIZE_EXTRA_LARGE = 160
