// TODO: CLIENT-3012 Define config for web to use .env files similar to app ones
export const Config = {
  BACKEND_SERVER_TYPE: process.env.NEXT_PUBLIC_BACKEND,
  // GraphQL URLs:
  GRAPHQL_URL_DEV: process.env.NEXT_PUBLIC_GRAPHQL_URL_DEV,
  GRAPHQL_URL_INTERNAL: process.env.GRAPHQL_URL_INTERNAL,
  GRAPHQL_URL_PUBLIC: process.env.NEXT_PUBLIC_GRAPHQL_URL_PUBLIC,
  GRAPHQL_URL_INT_INTERNAL: process.env.GRAPHQL_URL_INT_INTERNAL,
  GRAPHQL_URL_INT_PUBLIC: process.env.NEXT_PUBLIC_GRAPHQL_URL_INT_PUBLIC,
  GRAPHQL_URL_STG_INTERNAL: process.env.GRAPHQL_URL_STG_INTERNAL,
  GRAPHQL_URL_STG_PUBLIC: process.env.NEXT_PUBLIC_GRAPHQL_URL_STG_PUBLIC,
  // Websites:
  WEBSITE: process.env.NEXT_PUBLIC_WEBSITE,
  WEBSITE_DEV: process.env.NEXT_PUBLIC_WEBSITE_DEV,
  WEBSITE_INT: process.env.NEXT_PUBLIC_WEBSITE_INT,
  WEBSITE_STG: process.env.NEXT_PUBLIC_WEBSITE_STG,
}
